version: '3.9'

services:
  app:
    image: crypto-exchanger
    command: make start_production
    restart: unless-stopped
    environment:
      RAILS_ENV: production
    volumes:
      - .:/code
    stdin_open: true
    tty: true
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    depends_on:
      - pg

  pg:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postrgess:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
          constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx
    volumes:
      - ./.deploy/nginx/conf.d/:/etc/nginx/conf.d/
      - ./public:/usr/share/nginx/html
    depends_on:
      - app
    restart: unless-stopped
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    networks:
      - my_network
      - default

volumes:
  postrgess:

networks:
  my_network:
    external: true